export const acceptedList = [
  [1, "Souvik Sur and Dipanwita Roy Chowdhury", "Verifiable Delay Function Based on Non-linear Hybrid Cellular Automata", 17],
  [2, "Bijoy Das, Abhijit Das and Dipanwita Roy Chowdhury", "Security Analysis of WG-7 Lightweight Stream Cipher against Cube Attack", 30],
  [3, "Manoj Kumar and Tarun Yadav", "MILP Modeling of S-box: Divide and Merge Approach", 31],
  [4, "Rani Deb and Ak Das", "More on semipositive tensor and tensor complementarity problem", 32],
  [5, "Jugal Mohapatra and S Priyadarshana", "An improved numerical scheme for semilinear singularly perturbed parabolic delay differential equations", 33],
  [6, "Dhruvil Bhatt, Kirtan Delwadia, Shishir Purohit and Bhaskar Chaudhury", "Computational Modeling of Noisy Plasma Images applicable to Tokamak Imaging Diagnostics for Visible and X-ray Emissions", 37],
  [7, "Nitin Gupta and Santosh Kumar Chaudhary", "On partial monotonicity of some extropy measures", 42],
  [8, "Bharat Kumar, Deepmala Deepmala, A Dutta and A K Das", "Error Bound for the Linear Complementarity Problem using Plus Function", 43],
  [9, "Ednalyn Xyra Calabia and Jerico Bacani", "On the solutions of the Diophantine equation $u^a + v^b = z^2$ for some prime pairs u and v", 44],
  [10, "Sourav Saha, Ashok Kumar Das and Debasis Giri", "Private Blockchain Enabled Security Framework for IoT-Based Healthcare System", 50],
  [11, "Sushree Priyadarshana and Jugal Mohapatra", "A second order optimal hybrid scheme for singularly perturbed semilinear parabolic problems with interior layers", 51],
  [12, "Bhagya Shree Meena and Dr. Sushil Kumar", "Temperature distribution during hyperthermia using a 2D space-time fractional bioheat model in irregular domain", 55],
  [13, "Manjeet Kaur, Tarun Yadav, Manoj Kumar and Dhananjoy Dey", "A Relation between Properties of S-box and Linear Inequalities of DDT", 61],
  [14, "Paul Immanuel and A. Berin Greeni", "Characterization of Minimum Structure and Sub-structure Cut of Exchanged Hypercube", 70],
  [15, "Subhasis Koley and Sasthi Ghosh", "Optimal $L(1,2)$-edge Labeling of Infinite Octagonal Grid", 72],
  [16, "Susmita Saha and Soumen De", "Damage level estimation of rubble-mound breakwaters using deep artificial neural network", 73],
  [17, "Sounava Pal, Sourav Mandal and Rohini Basak", "Classification of Texts with Emojis to Classify Sentiments, Moods, and Emotions", 76],
  [18, "Rakesh Kumar Meena and Sushil Kumar", "A Study on Fractional SIS Epidemic Model Using RPS Method", 84],
  [19, "Sagnik Sinha and Kushal Guha Bakshi", "On Zero-Sum Two Person Perfect Information Semi-Markov Games", 88],
  [20, "Shramona Chakraborty and Dipanwita Roy Chowdhury", "Facial Image Manipulation Detection using Cellular Automata and Transfer Learning", 89],
  [21, "Habiba Khatun and Manas Tripathy", "Interval Estimation for Quantiles of Several Normal Populations with a Common Standard Deviation", 109],
  [22, "Nishi Gupta and Md. Maqbul", "Approximate solutions to delay diffusion equations with integral forcing function", 112],
  [23, "Helda Rajendran and Kalpana Mahalingam", "On m-bonacci intersection-sum graphs", 113],
  [24, "Pradeep Sahu, Kuldip Patel and Ratikanta Behera", "Three-time levels compact scheme for pricing European options under regime switching jump-diffusion models", 115],
  [25, "Karen Taclay and Richard Taclay", "Lorentz Matrices in $M_2(\\mathbb{Z}_n)$", 121],
  [26, "Vishalkumar J. Prajapati and Ramakanta Meher", "A robust analytic approach to solve non-linear fractional partial differential equations using fractional complex transform", 124],
  [27, "Sri Sakti Swarup Anupindi and Michael Alphonse", "Relations Between Discrete Maximal Operators in Harmonic Analysis", 129],
  // [28, "Abhishek Kumar Singh", "Numerical analysis of boundary layer flows with temperature sensitive parameters and validation using ANSYS FLUENT", 130],
  [28, "Sujit Kumar, Mohan Kumar and Sanasam Ranbir Singh", "Language Independent Fake News Detection Over Social Media Networks Using Centrality Aware Graph Convolution Network", 132],
  [39, "Snigdha Mayee Samantray, Debasis Giri and Tanmoy Maitra", "GradeChain: a Hyperledger Fabric Blockchain based Students’ Grading System for Educational Institute", 133],
  [30, "Shyamalendu Kandar and Seba Maity", "Object-Background Partitioning on Images: A Ratio based Division", 134],
  [31, "D. Kumar, A. K. B. Chand and P. R. Massopust", "Multivariate Bernstein α-Fractal Functions", 135]
]
